var tap = require('tap');
var renderMarkdown = require('../safe-markdown');

var XSS_PAYLOADS = [
  '<script>alert(1)</script>',
  '<img src=x onerror=alert(1)>',
  '<IMG SRC="jav&#x09;ascript:alert(1)">',
  '<a href="javascript:alert(1)">click</a>',
  '<svg/onload=alert(1)>',
  '<div onmouseover="alert(1)">hover</div>',
  '[click](javascript:alert(1))',
  '[click](javascript&#x3a;alert(1))',
  '[click](javascript&#X3A;alert(1))',
  '[click](java\nscript:alert(1))',
  '[click](JaVaScRiPt:alert(1))',
  '[click](data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==)',
  '[click](vbscript:msgbox(1))',
  '![img](javascript:alert(1))',
  '![img](x" onerror="alert(1))',
  '[click](" onclick="alert(1))',
  '[click](http://x.tld " onmouseover="alert(1))',
  '<bar"onclick="alert(1)"@foo>',
  '<<script>alert(1)//<</script>',
  '&#60;script&#62;alert(1)&#60;/script&#62;'
];

// attribute values are html escaped, so no tag can contain a raw quote or angle
// bracket and the markup can be walked with a regexp
var ALLOWED_TAGS = /^<\/?(p|a|img|strong|em|code|pre|blockquote|ul|ol|li|h[1-6]|hr|br|del|table|thead|tbody|tr|th|td)(\s[^>]*)?\/?>$/i;
var ALLOWED_ATTRIBUTES = /^(href|src|alt|title|rel|id|class|align)$/;

tap.test('markdown output never contains attacker injected markup', function (t) {
  XSS_PAYLOADS.forEach(function (payload) {
    var html = renderMarkdown(payload);

    (html.match(/<[^>]*>/g) || []).forEach(function (tag) {
      t.match(tag, ALLOWED_TAGS, 'tag is generated by the renderer: ' + tag);

      // every attribute value is quoted and escaped, so the attribute names of
      // the tag are exactly the quoted assignments in it
      (tag.match(/\s[a-zA-Z][a-zA-Z0-9-]*\s*=\s*"[^"]*"/g) || []).forEach(function (attribute) {
        var name = attribute.trim().split(/\s*=/)[0].toLowerCase();
        t.match(name, ALLOWED_ATTRIBUTES, 'attribute is generated by the renderer: ' + attribute);
      });

      t.notMatch(tag, /(href|src)\s*=\s*"\s*(javascript|vbscript|data)\s*(:|&#)/i,
        'no dangerous url in: ' + tag);
    });

    t.notMatch(html, /<script/i, 'no script tag for: ' + payload);
    t.notMatch(html, /<svg/i, 'no svg tag for: ' + payload);
  });
  t.end();
});

tap.test('safe markdown still renders', function (t) {
  t.match(renderMarkdown('**bold**'), /<strong>bold<\/strong>/);
  t.match(renderMarkdown('# title'), /<h1[^>]*>title<\/h1>/);
  t.match(renderMarkdown('* one\n* two'), /<li>one<\/li>/);
  t.match(renderMarkdown('[snyk](https://snyk.io)'), /<a href="https:\/\/snyk\.io"/);
  t.match(renderMarkdown('[mail](mailto:a@b.tld)'), /<a href="mailto:a@b\.tld"/);
  t.match(renderMarkdown('[rel](/edit/1)'), /<a href="\/edit\/1"/);
  t.match(renderMarkdown('![logo](https://snyk.io/logo.png)'), /<img src="https:\/\/snyk\.io\/logo\.png"/);
  t.end();
});

tap.test('non string content is handled', function (t) {
  t.equal(renderMarkdown(null), '');
  t.equal(renderMarkdown(undefined), '');
  t.match(renderMarkdown(new String('**bold**')), /<strong>bold<\/strong>/);
  t.end();
});
